import type { Metadata } from 'next';

import Left from '@/components/aside/Left';
import Right from '@/components/aside/Right';
import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';

import { spaceGrotesk } from '@/lib/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Kevin Cruz',
  description: 'Generated by Kevoff',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.className} grid min-h-screen grid-cols-[230px,1fr,230px] antialiased`}>
        <Left />
        <div className="border-x border-primary">
          <Header />
          {children}
          <Footer />
        </div>
        <Right />
      </body>
    </html>
  );
}
